use_frameworks!
platform :ios, '10.0'

target 'DTZFloatingActionButton_Example' do
  pod 'DTZFloatingActionButton', :path => '../'

  target 'DTZFloatingActionButton_Tests' do
    inherit! :search_paths

    
  end
end
